---
- hosts: default
  vars:
    postgresql_version: 9.3
    ruby_install_version: HEAD
    ruby_version: 2.1.2
  roles:
    - base
    - git
    - postgres
    - ruby-install
    - ruby
    - zsh
    - chruby
    - bundler
  sudo : true
