---
- name: Install Mysql
  apt: pkg=mysql-server state=present

- name: Launch the service if not started
  service: name=mysql state=started

- name: Install dependency for mysql gem building
  apt: pkg=libmysqlclient-dev state=present
