---
- name: Download chruby
  get_url: >
    url="https://github.com/postmodern/chruby/archive/v{{chruby_version}}.tar.gz"
    dest="/tmp/chruby.tar.gz"

- name: Extract chruby
  command: >
    tar -zxf /tmp/chruby.tar.gz
    creates="/home/{{user}}/chruby-{{chruby_version}}"

- name: Install chruby
  command: >
    make install
    chdir="/home/{{user}}/chruby-{{chruby_version}}"

- name: Add chruby to zshrc
  lineinfile: >
    dest="/home/{{user}}/.zshrc"
    line="source /usr/local/share/chruby/chruby.sh"

- name: Enable installed ruby version
  lineinfile:
    dest="/home/{{user}}/.zshrc"
    line="chruby ruby"
