---
- name: Clone chruby
  git: >
    repo="https://github.com/postmodern/chruby"
    dest="/home/{{user}}/chruby"
    version=v{{chruby_version}}
    accept_hostkey=true

- name: Install chruby
  command: >
    make install
    chdir="/home/{{user}}/chruby"

- name: Add chruby to zshrc
  lineinfile: >
    dest="/home/{{user}}/.zshrc"
    line="source /usr/local/share/chruby/chruby.sh"

- name: Enable installed ruby version
  lineinfile:
    dest="/home/{{user}}/.zshrc"
    line="chruby ruby"
